package com.example.go2apkapp;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.EditText;

public class MainActivity extends Activity {
    private LinearLayout main_layout;
    private TextView display;
    private LinearLayout row_1;
    private Button btn_7;
    private Button btn_8;
    private Button btn_9;
    private Button btn_div;
    private LinearLayout row_2;
    private Button btn_4;
    private Button btn_5;
    private Button btn_6;
    private Button btn_mul;
    private LinearLayout row_3;
    private Button btn_1;
    private Button btn_2;
    private Button btn_3;
    private Button btn_sub;
    private LinearLayout row_4;
    private Button btn_clear;
    private Button btn_0;
    private Button btn_eq;
    private Button btn_add;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle("Go2APK Calculator");
        setContentView(createAppView());
    }

    private View createAppView() {
        LinearLayout view1 = new LinearLayout(this);
        view1.setOrientation(LinearLayout.VERTICAL);
        view1.setGravity(Gravity.CENTER_HORIZONTAL);
        view1.setPadding(24, 24, 24, 24);
        this.main_layout = view1;
        LinearLayout rootView = view1;
        TextView view2 = new TextView(this);
        view2.setText("0");
        view2.setTextSize(24);
        this.display = view2;
        view1.addView(view2);
        LinearLayout view3 = new LinearLayout(this);
        view3.setOrientation(LinearLayout.HORIZONTAL);
        view3.setGravity(Gravity.CENTER);
        this.row_1 = view3;
        view1.addView(view3);
        Button view4 = new Button(this);
        view4.setText("7");
        this.btn_7 = view4;
        view3.addView(view4);
        Button view5 = new Button(this);
        view5.setText("8");
        this.btn_8 = view5;
        view3.addView(view5);
        Button view6 = new Button(this);
        view6.setText("9");
        this.btn_9 = view6;
        view3.addView(view6);
        Button view7 = new Button(this);
        view7.setText("/");
        this.btn_div = view7;
        view3.addView(view7);
        LinearLayout view8 = new LinearLayout(this);
        view8.setOrientation(LinearLayout.HORIZONTAL);
        view8.setGravity(Gravity.CENTER);
        this.row_2 = view8;
        view1.addView(view8);
        Button view9 = new Button(this);
        view9.setText("4");
        this.btn_4 = view9;
        view8.addView(view9);
        Button view10 = new Button(this);
        view10.setText("5");
        this.btn_5 = view10;
        view8.addView(view10);
        Button view11 = new Button(this);
        view11.setText("6");
        this.btn_6 = view11;
        view8.addView(view11);
        Button view12 = new Button(this);
        view12.setText("*");
        this.btn_mul = view12;
        view8.addView(view12);
        LinearLayout view13 = new LinearLayout(this);
        view13.setOrientation(LinearLayout.HORIZONTAL);
        view13.setGravity(Gravity.CENTER);
        this.row_3 = view13;
        view1.addView(view13);
        Button view14 = new Button(this);
        view14.setText("1");
        this.btn_1 = view14;
        view13.addView(view14);
        Button view15 = new Button(this);
        view15.setText("2");
        this.btn_2 = view15;
        view13.addView(view15);
        Button view16 = new Button(this);
        view16.setText("3");
        this.btn_3 = view16;
        view13.addView(view16);
        Button view17 = new Button(this);
        view17.setText("-");
        this.btn_sub = view17;
        view13.addView(view17);
        LinearLayout view18 = new LinearLayout(this);
        view18.setOrientation(LinearLayout.HORIZONTAL);
        view18.setGravity(Gravity.CENTER);
        this.row_4 = view18;
        view1.addView(view18);
        Button view19 = new Button(this);
        view19.setText("C");
        this.btn_clear = view19;
        view18.addView(view19);
        Button view20 = new Button(this);
        view20.setText("0");
        this.btn_0 = view20;
        view18.addView(view20);
        Button view21 = new Button(this);
        view21.setText("=");
        this.btn_eq = view21;
        view18.addView(view21);
        Button view22 = new Button(this);
        view22.setText("+");
        this.btn_add = view22;
        view18.addView(view22);
        return rootView;
    }
}
