package config

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Config contains the project metadata used to generate Android artifacts.
type Config struct {
	Name        string
	Package     string
	Version     string
	MinSDK      int
	TargetSDK   int
	Orientation string
	Theme       string
	Source      string
	Obfuscate   bool
}

// Default returns beginner-friendly Android application defaults.
func Default() Config {
	return Config{
		Name:        "Go2APK Calculator",
		Package:     "com.example.go2apkapp",
		Version:     "0.1.0",
		MinSDK:      23,
		TargetSDK:   36,
		Orientation: "unspecified",
		Theme:       "@style/AppTheme",
		Source:      "./examples/demo",
		Obfuscate:   false,
	}
}

// Load reads go2apk.yaml values. It intentionally supports the simple
// key: value format generated by go2apk init so the CLI has no YAML runtime dependency.
func Load(path string) (Config, error) {
	cfg := Default()
	file, err := os.Open(path)
	if err != nil {
		return cfg, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			return cfg, fmt.Errorf("invalid config line %q; expected key: value", line)
		}
		key = strings.TrimSpace(key)
		value = strings.Trim(strings.TrimSpace(value), "\"'")
		switch key {
		case "name":
			cfg.Name = value
		case "package":
			cfg.Package = value
		case "version":
			cfg.Version = value
		case "min_sdk":
			cfg.MinSDK, err = atoi(key, value)
		case "target_sdk":
			cfg.TargetSDK, err = atoi(key, value)
		case "orientation":
			cfg.Orientation = value
		case "theme":
			cfg.Theme = value
		case "source":
			cfg.Source = value
		case "obfuscate":
			cfg.Obfuscate, err = atob(key, value)
		}
		if err != nil {
			return cfg, err
		}
	}
	return cfg, scanner.Err()
}

func atoi(key, value string) (int, error) {
	n, err := strconv.Atoi(value)
	if err != nil {
		return 0, fmt.Errorf("invalid %s value %q: %w", key, value, err)
	}
	return n, nil
}

func atob(key, value string) (bool, error) {
	b, err := strconv.ParseBool(value)
	if err != nil {
		return false, fmt.Errorf("invalid %s value %q: %w", key, value, err)
	}
	return b, nil
}
